Repository googleapis/docuploader, pull requests merged in 2021-02, with the labels that each got.

#52 fix: update destination_prefix to allow 'docfx-'
  docuploader/__main__.py
Labels: automerge, cla: yes

#41 build(python): use release-publish app for GitHub release status
  .kokoro/build.sh
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:force-run

#56 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full
