Repository googleapis/docuploader, pull requests merged in 2021-01, with the labels that each got.

#43 feat: adding timeout argument to be passable
  docuploader/shell.py
Labels: cla: yes, type: feature request

#46 feat: add xref docs.metadata fields
  docuploader/__main__.py
  docuploader/protos/metadata.proto
  docuploader/protos/metadata_pb2.py
  docuploader/protos/metadata_pb2.pyi
  docuploader/shell.py
  setup.py
Labels: automerge, cla: yes

#48 feat: adding docs.metadata.json support
  docuploader/__main__.py
Labels: cla: yes

#50 build: migrate to flakybot
  .kokoro/trampoline_v2.sh
Labels: cla: yes
